name: Prune Merged Branches

on:
  push:
    branches:
      - main # Replace with your default branch if different
  schedule:
    - cron: "0 0 * * 0" # Weekly on Sunday at midnight

jobs:
  prune:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important: fetch all history to evaluate merged branches

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch all remote branches
        run: git fetch --prune origin

      - name: Prune Merged Branches
        run: |
          echo "Pruning merged branches..."
          git branch -r --merged origin/main | grep -vE 'main|dev|HEAD|release/|hotfix/' | sed 's/origin\///' | while read branch; do
            echo "Deleting merged branch: $branch"
            git push origin --delete "$branch"
          done
